version: "3.9"

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - redis1
      - redis2
      - redis3

  redis1:
    image: "redis:latest"
    container_name: redis1
    ports:
      - "6379:6379"
    volumes:
      - ./redis_config/redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    networks:
      default:
        aliases:
          - redis1

  redis2:
    image: "redis:latest"
    container_name: redis2
    ports:
      - "6380:6379"
    volumes:
      - ./redis_config/redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    networks:
      default:
        aliases:
          - redis2

  redis3:
    image: "redis:latest"
    container_name: redis3
    ports:
      - "6381:6379"
    volumes:
      - ./redis_config/redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    networks:
      default:
        aliases:
          - redis3
